### ISSUE TITLE
Using requests vs urllib3 

### ISSUE THREAD

**Issue by LukaData** [adswerve/GA4-Measurement-Protocol-Python#3]
The requests module is an additional requirement. Opening up for debate if it should be replaced by a native library.

**Comment by DanReia** [comment]
@zachmitch @LukaData I have been looking into this and urllib3 is also an external module (not included in Python3 standard library) and is also a dependency of the requests library.

Given the additional functionality and ease of use of requests, I think we should stick with it instead of resorting to urllib. Including requests as a required install, pip will automatically handle the dependency and the user will not need to install it manually. If we get to a point where we need to decode event data, it will make our lives a lot easier. 

Interestingly, the standard library docs recommend requests: https://docs.python.org/3/library/urllib.request.html#module-urllib.request see "See Also"

**Comment by DanReia** [comment]
After speaking to Anže, went ahead and replaced it, [PR#23](https://github.com/adswerve/GA4-Measurement-Protocol-Python/pull/23) open to resolve
